- block:
  - name: set fact
    set_fact:
      src_path: "{{ deb }}"
      file_name: "{{ deb | basename}}"

  - name: create deb directory
    file:
      path: /home/admin/debs
      state: directory
      owner: admin
      mode: "700"

  - block:
    - name: copy deb file to remote
      copy:
        src: "{{ src_path }}"
        dest: /home/admin/debs/
        owner: admin
        group: admin
    
    - block:
      - name: copy deb file into containers
        shell: docker cp /home/admin/debs/{{ file_name }} {{ target }}:/home/

      - name: install deb file inside container
        shell: docker exec {{ target }} dpkg -i /home/{{ file_name }}
      when: target != "host"
      
    - name: install deb file on host
      shell: dpkg -i /home/admin/debs/{{ file_name }}
      become: yes
      when: target == "host"
    
    when: deb is defined and target is defined
    

