- block:
  - name: set fact
    set_fact:
      src_dir: "{{restore_dir}}/{{inventory_hostname}}"
      login: "{{ansible_user}}@{{ansible_host}}"
      dst_sonic_command: '"cat > {{config_db_dir}}/config_db.json"'
      dst_frr_command: '"cat > {{frr_dir}}/frr.conf"'

  - name: restore config_db.json
    shell: cat {{src_dir}}/config_db.json | sshpass -p {{ansible_password}} ssh -q -o StrictHostKeyChecking=no {{login}} 'sudo sh -c {{dst_sonic_command}}'
    delegate_to: localhost
    when: restore_dir is defined

  - name: restore frr.conf
    shell: cat {{src_dir}}/frr.conf | sshpass -p {{ansible_password}} ssh -q -o StrictHostKeyChecking=no {{login}} 'sudo sh -c {{dst_frr_command}}'
    delegate_to: localhost
    when: restore_dir is defined