all:
  children:
    sonic:
      hosts:
        spine-1:
          ansible_host: 192.168.8.121
        spine-2:
          ansible_host: 192.168.8.122
        leaf-1:
          ansible_host: 192.168.8.123
        leaf-2:
          ansible_host: 192.168.8.124
        ext-leaf-1:
          ansible_host: 192.168.8.125
        ext-leaf-2:
          ansible_host: 192.168.8.126

